import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Card } from "./Components/Card/Card";
import { fetchLaunchData } from "../utils/helpers";

// Example of using next/Image
// <Image src='https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png' alt='ss' width='200px' height='200px'/>

const Home: React.FC = () => {
  const [launchData, setLaunchData] = useState([]);
  const [loading, setLoading] = useState(false);

  const getLaunchData = async () => {
    const launches = await fetchLaunchData();
    if (launches) {
      setLaunchData(launches);
      setLoading(true);
    }
  };

  useEffect(() => {
    getLaunchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Image
          src="https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png"
          alt="ss"
          width="200px"
          height="200px"
        />

        {loading &&
          launchData?.map((launch) => {
            return (
              <ul key={launch.flight_number}>
                <Card launch={launch} />
              </ul>
            );
          })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
